# ---------------------------------------------------------
# CodeRabbit AI Review Config for Frontend (React/Vite)
# Author: Anshul (AllCognix Media Studios)
# ---------------------------------------------------------

language: auto

review:
  enable_summary: true
  enable_inline_comments: true
  focus_areas:
    - readability
    - performance
    - maintainability
    - security

  comment_style: friendly
  max_comments: 30   # limit number of inline comments per PR

  exclude_paths:
    - node_modules/**
    - dist/**
    - build/**
    - coverage/**
    - public/**
    - .github/**
    - .vscode/**
    - .husky/**

rules:
  javascript:
    prefer_const: true
    avoid_console: true
    no_direct_dom_access: true
  react:
    hooks_best_practices: true
    check_missing_dependencies: true
    enforce_component_naming: true
    prevent_unused_states: true

labels:
  reviewed_by_ai: true
  label_name: "AI-Reviewed ✅"
