# ---------------------------------------------------------
# CodeRabbit AI Review Config for React Frontend
# Author: Anshul (AllCognix Media Studios)
# ---------------------------------------------------------

language: en-US

# Friendly, constructive tone + focus areas
tone_instructions: |
  Be friendly and constructive. Focus on readability, performance,
  maintainability, security, and accessibility. Prefer concise suggestions
  with concrete diffs/examples when possible.

reviews:
  profile: chill                # or "assertive" if you want stricter
  high_level_summary: true
  review_status: true
  commit_status: true
  fail_commit_status: false     # don't fail the status if issues found

  auto_review:
    enabled: true               # auto-review PRs
    drafts: false               # skip drafts (set true if you want)

# File selection (exclude heavy/generated stuff)
path_filters:
  exclude:
    - "node_modules/**"
    - "dist/**"
    - "build/**"
    - "coverage/**"
    - "public/**"
    - ".github/**"
    - ".vscode/**"
    - ".husky/**"

# Built-in tooling hooks CodeRabbit can run alongside reviews
tools:
  eslint:
    enabled: true               # allow JS/TS lint hints during review
